
common:
  output_dir:
    default: /eos/user/c/cerminar/hgcal/CMSSW1015/plots/
    matterhorn: /Users/cerminar/cernbox/hgcal/CMSSW1015/plots/
    Matterhorn: /Users/cerminar/cernbox/hgcal/CMSSW1015/plots/
  output_dir_local: /Users/cerminar/cernbox/hgcal/CMSSW1015/plots/
  output_dir_lx: /eos/user/c/cerminar/hgcal/CMSSW1015/plots/
  plot_version: v150
  run_clustering: False
  run_density_computation: False
# +AccountingGroup = "group_u_CMS.u_zh.users"
# +AccountingGroup = "group_u_CMST3.all"

collections:

  nugun_tracks:
    file_label:
      tracks
    samples:
      - nugun_alleta_pu200
    plotters:
      - track_plotters
      # - tkeg_plotters
      - eg_rate_plotters
    htc_jobflavor:
      workday
    priorities:
      nugun_alleta_pu200: 0
    events_per_job:
      nugun_alleta_pu200: 10

  single_empart_guns_tracks:
    file_label:
      eg
    samples:
      - doubleele_flat1to100_PU0
      - doubleele_flat1to100_PU200
      # - ele_flat2to100_PU0
      # - ele_flat2to100_PU200
    plotters:
      # - track_plotters
      - track_genmatched_plotters
      # - tkeg_plotters
      # - eg_genmatched_plotters
    htc_jobflavor:
      workday
    priorities:
      ele_flat2to100_PU0: 1
      ele_flat2to100_PU200: 5
      doubleele_flat1to100_PU0: 1
      doubleele_flat1to100_PU200: 5
    events_per_job:
      # ele_flat2to100_PU0: 1
      # ele_flat2to100_PU200: 5
      # photon_flat8to150_PU0: 0
      # photon_flat8to150_PU200: 0
      doubleele_flat1to100_PU0: 2100
      doubleele_flat1to100_PU200: 800
      doublephoton_flat1to100_PU200: 800

  single_empart_guns_isostudy:
    file_label:
      eg
    samples:
      # - ele_flat2to100_PU0
      # - ele_flat2to100_PU200
      # - doubleele_flat1to100_PU0
      - doubleele_flat1to100_PU200
      - doublephoton_flat1to100_PU200
      # - photon_flat8to150_PU0
      # - photon_flat8to150_PU200
      # - dyll_PU200
    plotters:
      # - eg_plotters
      - eg_genmatched_plotters_iso
    htc_jobflavor:
      longlunch
    priorities:
      ele_flat2to100_PU0: 1
      ele_flat2to100_PU200: 5
      doublephoton_flat1to100_PU200: 6
      photon_flat8to150_PU0: 0
      photon_flat8to150_PU200: 0
      doubleele_flat1to100_PU0: 2
      doubleele_flat1to100_PU200: 7
    events_per_job:
      # ele_flat2to100_PU0: 1
      # ele_flat2to100_PU200: 5
      # photon_flat8to150_PU0: 0
      # photon_flat8to150_PU200: 0
      doubleele_flat1to100_PU0: 2000
      doubleele_flat1to100_PU200: 10000
      doublephoton_flat1to100_PU200: 2000


  single_empart_guns_egvalid:
    file_label:
      eg
    samples:
      # - ele_flat2to100_PU0
      # - ele_flat2to100_PU200
      # - doubleele_flat1to100_PU0
      - doubleele_flat1to100_PU200
      - doublephoton_flat1to100_PU200
      # - photon_flat8to150_PU0
      # - photon_flat8to150_PU200
      # - dyll_PU200
    plotters:
      - eg_plotters
      - eg_genmatched_plotters
    htc_jobflavor:
      microcentury
    priorities:
      ele_flat2to100_PU0: 1
      ele_flat2to100_PU200: 5
      doublephoton_flat1to100_PU200: 6
      photon_flat8to150_PU0: 0
      photon_flat8to150_PU200: 0
      doubleele_flat1to100_PU0: 2
      doubleele_flat1to100_PU200: 7
    events_per_job:
      # ele_flat2to100_PU0: 1
      # ele_flat2to100_PU200: 5
      # photon_flat8to150_PU0: 0
      # photon_flat8to150_PU200: 0
      doubleele_flat1to100_PU0: 5000
      doubleele_flat1to100_PU200: 3000
      doublephoton_flat1to100_PU200: 5000

      # dyll_PU200: 5

  # electron_eff_eg:
  #   file_label:
  #     eg
  #   samples:
  #     - ele_flat2to100_PU0
  #     - ele_flat2to100_PU200
  #     # - dyll_PU200
  #   plotters:
  #     - ele_genmatched_plotters
  #   htc_jobflavor:
  #     tomorrow
  #   priorities:
  #     ele_flat2to100_PU0: 1
  #     ele_flat2to100_PU200: 5
  #     dyll_PU200: 4
  #   weights:
  #     dyll_PU200: data/dyll_pt_weights.root


  # single_empart_guns_resotuples:
  #   file_label:
  #     reso
  #   samples:
  #     - ele_flat2to100_PU0
  #     - ele_flat2to100_PU200
  #     # - photon_flat8to150_PU0
  #     # - photon_flat8to150_PU200
  #   plotters:
  #     - eg_resotuples_plotters
  #     - tp_resotuples_plotters
  #   htc_jobflavor:
  #     workday
  #   priorities:
  #     ele_flat2to100_PU0: 1
  #     ele_flat2to100_PU200: 5
  #     photon_flat8to150_PU0: 0
  #     photon_flat8to150_PU200: 0

  # single_empart_guns_calibs:
  #   file_label:
  #     calibs
  #   samples:
  #     - ele_flat2to100_PU0
  #     - ele_flat2to100_PU200
  #     - photon_flat8to150_PU0
  #     # - photon_flat8to150_PU200
  #   plotters:
  #     - tp_calib_plotters
  #     # - ttower_plotters
  #     # - ttower_genmatched_plotters
  #   htc_jobflavor:
  #     microcentury
  #   priorities:
  #     ele_flat2to100_PU0: 5
  #     ele_flat2to100_PU200: 3
  #     photon_flat8to150_PU0: 4
  #     photon_flat8to150_PU200: 1

  # single_empart_guns_tps:
  #   file_label:
  #     tps
  #   samples:
  #     - doubleele_flat1to100_PU200
  #     # - ele_flat2to100_PU0
  #     # - ele_flat2to100_PU200
  #     # - photon_flat8to150_PU0
  #     # - photon_flat8to150_PU200
  #   plotters:
  #     - tp_plotters
  #     - tp_genmatched_plotters
  #     - genpart_plotters
  #     # - ttower_plotters
  #     # - ttower_genmatched_plotters
  #   htc_jobflavor:
  #     tomorrow
  #   priorities:
  #     ele_flat2to100_PU0: 1
  #     ele_flat2to100_PU200: 5
  #     photon_flat8to150_PU0: 0
  #     photon_flat8to150_PU200: 4
  #     doubleele_flat1to100_PU200: 5
  #   events_per_job:
  #     ele_flat2to100_PU0: 1
  #     ele_flat2to100_PU200: 5
  #     photon_flat8to150_PU0: 0
  #     photon_flat8to150_PU200: 0
  #     doubleele_flat1to100_PU0: 2100
  #     doubleele_flat1to100_PU200: 800
  #     doublephoton_flat1to100_PU200: 800
  # 
  # 
  # highpt_tps:
  #   file_label:
  #     tps
  #   samples:
  #     - zprime_ee_PU200
  #   plotters:
  #     # - tp_plotters
  #     - tp_genmatched_extrange_plotters
  #     # - genpart_plotters
  #     # - ttower_plotters
  #     # - ttower_genmatched_plotters
  #   htc_jobflavor:
  #     workday
  #   priorities:
  #     zprime_ee_PU200: 5
  #   events_per_job:
  #     zprime_ee_PU200: 2000
  # 
  # single_had_guns_tps:
  #   file_label:
  #     tps
  #   samples:
  #     - pion_flat2to100_PU0
  #     - pion_flat2to100_PU200
  #   plotters:
  #     - tp_plotters
  #     - tp_genmatched_plotters
  #     - genpart_plotters
  #     # - ttower_plotters
  #     # - ttower_genmatched_plotters
  #   htc_jobflavor:
  #     tomorrow
  #   priorities:
  #     pion_flat2to100_PU0: 0
  #     pion_flat2to100_PU200: 0

  correlator_occupancy:
    file_label:
      pf
    samples:
      - ttbar_PU200
      # - dyll_PU200
    plotters:
      - correlator_occupancy_plotters
      - pftrack_plotters
    htc_jobflavor:
      microcentury
    priorities:
      ttbar_PU200: 3
      # dyll_PU200: 1
    events_per_job:
      ttbar_PU200: 200

  nugun_rate:
    file_label:
      rate
    samples:
      - nugun_alleta_pu200
    plotters:
      # - rate_plotters
      # - ttower_plotters
      # - tp_plotters
      # - eg_plotters
      - eg_rate_plotters
    htc_jobflavor:
      microcentury
    priorities:
      nugun_alleta_pu200: 6
    events_per_job:
      nugun_alleta_pu200: 20000

  # noise_samples:
  #   file_label:
  #     noise
  #   samples:
  #     - nugun_alleta_pu0
  #     - nugun_alleta_pu200
  #     # - nugun_endcap_PU50
  #     # - nugun_endcap_PU100
  #     # - nugun_endcap_PU140
  #     # - nugun_endcap_PU200
  #   plotters:
  #     # - rate_plotters
  #     - ttower_plotters
  #     # - tp_plotters
  #     # - eg_rate_plotters
  #   htc_jobflavor:
  #     workday
  #   priorities:
  #     nugun_alleta_pu0: 0
  #     nugun_alleta_pu200: 0

  # single_empart_guns_tccluster_matcher:
  #   file_label:
  #     tccl
  #   samples:
  #     - ele_flat2to100_PU0
  #     # - ele_flat2to100_PU200
  #     - photon_flat8to150_PU0
  #     # - photon_flat8to150_PU200
  #   plotters:
  #     # - tp_plotters
  #     - tp_cluster_tc_match_plotters
  #     # - ttower_plotters
  #     # - ttower_genmatched_plotters
  #   htc_jobflavor:
  #     microcentury
  #   priorities:
  #     ele_flat2to100_PU0: 5
  #     ele_flat2to100_PU200: 3
  #     photon_flat8to150_PU0: 4
  #     photon_flat8to150_PU200: 2
      

  isostudy_eg:
    file_label:
      iso
    samples:
      # - ele_flat2to100_PU0
      # - ele_flat2to100_PU200
      # - doubleele_flat1to100_PU0
      - doublephoton_flat1to100_PU200
      - doubleele_flat1to100_PU200
      - nugun_alleta_pu200
      # - photon_flat8to150_PU0
      # - photon_flat8to150_PU200
      # - dyll_PU200
    plotters:
      - eg_isotuples_plotters
    htc_jobflavor:
      microcentury
    priorities:
      nugun_alleta_pu200: 6
      ele_flat2to100_PU0: 1
      ele_flat2to100_PU200: 5
      photon_flat8to150_PU0: 0
      photon_flat8to150_PU200: 0
      doubleele_flat1to100_PU0: 2
      doubleele_flat1to100_PU200: 7
      doublephoton_flat1to100_PU200: 6
    events_per_job:
      doubleele_flat1to100_PU0: 10000
      doubleele_flat1to100_PU200: 20000
      doublephoton_flat1to100_PU200: 20000
      nugun_alleta_pu200: 11000

  decoded_tk:
    file_label:
      dtk
    samples:
      # - ele_flat2to100_PU0
      # - ele_flat2to100_PU200
      # - doubleele_flat1to100_PU0
      - doubleele_flat1to100_PU200
      # - nugun_alleta_pu200
      # - photon_flat8to150_PU0
      # - photon_flat8to150_PU200
      # - dyll_PU200
    plotters:
      - decTk_plotters
    htc_jobflavor:
      microcentury
    priorities:
      nugun_alleta_pu200: 6
      ele_flat2to100_PU0: 1
      ele_flat2to100_PU200: 5
      photon_flat8to150_PU0: 0
      photon_flat8to150_PU200: 0
      doubleele_flat1to100_PU0: 2
      doubleele_flat1to100_PU200: 7
      doublephoton_flat1to100_PU200: 6
    events_per_job:
      doubleele_flat1to100_PU0: 10000
      doubleele_flat1to100_PU200: 30000
      doublephoton_flat1to100_PU200: 20000
      nugun_alleta_pu200: 11000


plotters:
  rate_plotters: !!python/name:python.plotters_config.rate_plotters
  tp_plotters: !!python/name:python.plotters_config.tp_plotters
  tp_genmatched_plotters: !!python/name:python.plotters_config.tp_genmatched_plotters
  tp_genmatched_extrange_plotters: !!python/name:python.plotters_config.tp_genmatched_extrange_plotters
  genpart_plotters: !!python/name:python.plotters_config.genpart_plotters
  ttower_plotters: !!python/name:python.plotters_config.ttower_plotters
  ttower_genmatched_plotters: !!python/name:python.plotters_config.ttower_genmatched_plotters
  eg_plotters: !!python/name:python.plotters_config.eg_plotters
  eg_genmatched_plotters: !!python/name:python.plotters_config.eg_genmatched_plotters
  eg_genmatched_plotters_iso: !!python/name:python.plotters_config.eg_genmatched_plotters_iso
  ele_genmatched_plotters: !!python/name:python.plotters_config.ele_genmatched_plotters
  eg_rate_plotters: !!python/name:python.plotters_config.eg_rate_plotters
  track_plotters: !!python/name:python.plotters_config.track_plotters
  track_genmatched_plotters: !!python/name:python.plotters_config.track_genmatched_plotters
  # tkeg_plotters: !!python/name:python.plotters_config.tkeg_plotters
  tp_calib_plotters: !!python/name:python.plotters_config.tp_calib_plotters
  correlator_occupancy_plotters: !!python/name:python.plotters_config.correlator_occupancy_plotters
  pftrack_plotters: !!python/name:python.plotters_config.pftrack_plotters
  eg_resotuples_plotters: !!python/name:python.plotters_config.eg_resotuples_plotters
  tp_resotuples_plotters: !!python/name:python.plotters_config.tp_resotuples_plotters
  tp_cluster_tc_match_plotters: !!python/name:python.plotters_config.tp_cluster_tc_match_plotters
  eg_isotuples_plotters: !!python/name:python.plotters_config.eg_isotuples_plotters
  decTk_plotters: !!python/name:python.plotters_config.decTk_plotters
    # tp_set: !null,
    # tp_selection: !!python/name:python.selections.tp_match_selections}
#  gen_selection: gen_part_selections
# - plotter: TPPlotter
#   tp_selection: tp_eta_selections
#   gen_selection: gen_part_selections
