executable            = TEMPL_TASKDIR/run_harvest.sh
arguments             = $(ClusterID) $(JOB_ID)
output                = TEMPL_TASKDIR/logs/harvest_$(JOB_ID).$(ClusterId).$(ProcId).out
error                 = TEMPL_TASKDIR/logs/harvest_$(JOB_ID).$(ClusterId).$(ProcId).err
log                   = TEMPL_TASKDIR/logs/condor.harvest.$(ClusterId).log
+JobFlavour           = "tomorrow"

RequestCpus = 3

transfer_input_files  = ../ntuple-tools.tar.gz

transfer_output_files   = ""
queue
