executable            = TEMPL_TASKDIR/run_batch_cleanup.sh
arguments             = $(ClusterID) $(ProcId)
output                = TEMPL_TASKDIR/logs/cleanup.$(ClusterId).$(ProcId).out
error                 = TEMPL_TASKDIR/logs/cleanup.$(ClusterId).$(ProcId).err
log                   = TEMPL_TASKDIR/logs/condor_cleanup.$(ClusterId).log
+JobFlavour           = "espresso"
RequestCpus = 1

transfer_output_files   = ""
queue
